foreach(source_file IN LISTS QT_QML_CPP_FILES QT_QML_HEADER_FILES QT_QML_QML_FILES)
  if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${source_file}")
    message(FATAL_ERROR "Missing Qt QML source file: ${source_file}")
  endif()
  file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/${source_file}" source_lines)
  list(LENGTH source_lines source_line_count)
  if(source_line_count GREATER 500)
    message(FATAL_ERROR "Qt QML source file exceeds 500 lines: ${source_file} (${source_line_count})")
  endif()
endforeach()
message(STATUS "Validated Qt QML source manifest (${CMAKE_CURRENT_SOURCE_DIR})")
