foreach(source_file IN LISTS QT_QML_CPP_FILES QT_QML_HEADER_FILES QT_QML_QML_FILES)
  if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${source_file}")
    message(FATAL_ERROR "Missing Qt QML source file: ${source_file}")
  endif()
  file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/${source_file}" source_lines)
  list(LENGTH source_lines source_line_count)
  if(source_line_count GREATER 500)
    message(FATAL_ERROR "Qt QML source file exceeds 500 lines: ${source_file} (${source_line_count})")
  endif()
endforeach()

function(require_source_contains source_file required_pattern reason)
  file(READ "${CMAKE_CURRENT_SOURCE_DIR}/${source_file}" source_text)
  if(NOT source_text MATCHES "${required_pattern}")
    message(FATAL_ERROR "${source_file}: ${reason}")
  endif()
endfunction()

function(require_source_omits source_file forbidden_pattern reason)
  file(READ "${CMAKE_CURRENT_SOURCE_DIR}/${source_file}" source_text)
  if(source_text MATCHES "${forbidden_pattern}")
    message(FATAL_ERROR "${source_file}: ${reason}")
  endif()
endfunction()

require_source_contains("qml/ActionButton.qml" "ToolTip\\.visible: hovered && ToolTip\\.text\\.length > 0" "tooltip fallback preview must remain visible while hovered")
require_source_omits("qml/ControlField.qml" "controlValue\\(control\\)[^\n]*\\|\\|" "control values must preserve falsy 0/false values")
require_source_omits("qml/LibraryList.qml" "rowData\\[modelData\\.id\\][^\n]*\\|\\|" "library rows must preserve falsy 0/false values")
require_source_contains("src/BundleLoader.cpp" "safeLocale" "locale must be validated before path use")
require_source_contains("src/BundleLoader.cpp" "resolvePagePath" "page references must be constrained to pages/")
require_source_contains("src/CommandRunner.cpp" "toDouble\\(&" "numeric constraints must check conversion success")
require_source_omits("src/Controller.cpp" "waitFor(Start|Finished)" "controller process handling must not block the UI thread")
require_source_contains("src/JsonUtils.cpp" "value\\.toArray\\(\\)" "valueToString must serialize arrays")
require_source_contains("src/StateStore.cpp" "decodeTomlString" "TOML-ish config loading must decode escaped backslashes")
require_source_omits("src/main.cpp" "QCoreApplication::arguments" "CLI-only modes must parse args before constructing QGuiApplication")
message(STATUS "Validated Qt QML source manifest (${CMAKE_CURRENT_SOURCE_DIR})")
