coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "WebUI/dist/**"
  - "WebUI/node_modules/**"
  - "aidocs/**"
