import { StyleSheet } from 'react-native';

export function palette(isDarkMode: boolean) {
  return isDarkMode
    ? {
        background: '#111827',
        panel: '#1f2937',
        foreground: '#f9fafb',
        muted: '#cbd5e1',
        border: '#334155',
        accent: '#93c5fd',
        accentSoft: '#172554',
        success: '#86efac',
        warning: '#fde68a',
        danger: '#fca5a5',
      }
    : {
        background: '#f8fafc',
        panel: '#ffffff',
        foreground: '#0f172a',
        muted: '#475569',
        border: '#cbd5e1',
        accent: '#2563eb',
        accentSoft: '#dbeafe',
        success: '#15803d',
        warning: '#b45309',
        danger: '#b91c1c',
      };
}

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  app: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    gap: 12,
  },
  headerTextWrap: { flex: 1, gap: 4 },
  headerTitle: { fontSize: 22, fontWeight: '700' },
  headerSubtitle: { fontSize: 13 },
  headerButton: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  headerButtonLabel: { fontWeight: '600' },
  centeredState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 12,
  },
  stateCard: {
    margin: 24,
    borderWidth: 1,
    borderRadius: 16,
  },
  stateTitle: { fontSize: 20, fontWeight: '700', textAlign: 'center' },
  stateBody: { fontSize: 14, lineHeight: 20, textAlign: 'center' },
  shell: { flex: 1 },
  shellBody: { flex: 1, flexDirection: 'row' },
  shellBodyRTL: { flexDirection: 'row-reverse' },
  shellToolbar: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
  },
  sidebar: {
    width: 240,
    borderRightWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 16,
    gap: 12,
  },
  sidebarRTL: { borderRightWidth: 0, borderLeftWidth: 1 },
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  bundleIconImage: { width: 40, height: 40, borderRadius: 10 },
  bundleIconEmoji: { fontSize: 32, width: 40, textAlign: 'center' },
  sidebarTitle: { fontSize: 16, fontWeight: '800' },
  sidebarSummary: { fontSize: 12, lineHeight: 16 },
  navBottom: {
    borderTopWidth: 1,
    marginTop: 12,
    paddingTop: 12,
  },
  sidebarGroupTitle: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 12,
    marginBottom: 6,
  },
  sidebarButton: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 6,
  },
  sidebarButtonLabel: { fontSize: 14, fontWeight: '600' },
  contentWrap: { flex: 1 },
  pageScroll: { flex: 1 },
  pageContent: { padding: 16, gap: 16 },
  pageHeader: { gap: 6 },
  pageTitle: { fontSize: 24, fontWeight: '700' },
  pageSummary: { fontSize: 14, lineHeight: 20 },
  card: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    gap: 12,
  },
  sectionTitle: { fontSize: 18, fontWeight: '700' },
  sectionSubtitle: { fontSize: 13, lineHeight: 18 },
  fieldWrap: { gap: 8 },
  fieldLabel: { fontSize: 14, fontWeight: '600' },
  helpText: { fontSize: 12, lineHeight: 17 },
  textInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  flexInput: { flex: 1, minWidth: 160 },
  inputButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  choiceWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  optionGroups: { gap: 10 },
  optionGroup: { gap: 6 },
  optionGroupTitle: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  choiceChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  choiceChipLabel: { fontSize: 13, fontWeight: '600' },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  actionButton: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 42,
  },
  actionButtonCompact: { minWidth: 42, alignItems: 'center' },
  actionButtonDisabled: {
    opacity: 0.6,
  },
  actionButtonLabel: { fontSize: 14, fontWeight: '700' },
  actionHint: { fontSize: 12 },
  smallButton: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignSelf: 'flex-start',
  },
  statusStack: { gap: 6 },
  inlineStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  libraryRow: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  libraryRowTitle: { fontSize: 15, fontWeight: '700' },
  infoPair: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  infoGridCell: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  infoKey: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  infoValue: { fontSize: 13 },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  pill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 11,
    fontWeight: '700',
  },
  emptyText: { fontSize: 13, fontStyle: 'italic' },
  setupHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    gap: 10,
  },
  setupStep: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  terminal: {
    borderTopWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  terminalTabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  terminalTab: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  terminalTabLabel: { fontSize: 12, fontWeight: '700' },
  terminalTabActions: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  tabActionButton: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  tabActionLabel: { fontSize: 11, fontWeight: '800' },
  terminalBody: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    minHeight: 140,
    maxHeight: 260,
  },
  terminalBodyText: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Cascadia Mono',
  },
  badge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    alignSelf: 'flex-start',
  },
  badgeLabel: { fontSize: 11, fontWeight: '700' },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  confirmationCard: {
    width: '100%',
    maxWidth: 520,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    gap: 12,
  },
});
