export const emojiIconMap = {
    "point.3.connected.trianglepath.dotted": "🧬",
    "doc.text": "📄",
    "doc.text.magnifyingglass": "🔎",
    "text.page": "📄",
    "text.page.badge.magnifyingglass": "🔎",
    "text.badge.checkmark": "✅",
    "doc.badge.gearshape": "⚙️",
    stethoscope: "🩺",
    "waveform.path.ecg": "〰️",
    "waveform.path.ecg.rectangle": "🩺",
    "person.2.wave.2": "👥",
    "person.3.sequence": "👨‍👩‍👧",
    pawprint: "🐾",
    tree: "🌳",
    "books.vertical": "📚",
    folder: "📁",
    "folder.badge.gearshape": "🗂️",
    externaldrive: "💽",
    "externaldrive.connected.to.line.below": "💽",
    terminal: "▸",
    scissors: "✂️",
    hammer: "🔨",
    "square.grid.3x3": "▦",
    tablecells: "▦",
    "arrow.down.circle": "⬇️",
    "arrow.clockwise": "🔄",
    "arrow.clockwise.circle": "🔄",
    "arrow.triangle.2.circlepath": "🔁",
    "arrow.triangle.merge": "🔀",
    checklist: "☑️",
    "checkmark.circle.fill": "✅",
    "checkmark.seal": "✓",
    "number.circle": "#",
    trash: "🗑️",
    "trash.fill": "🗑️",
    gearshape: "⚙️",
    globe: "🌐",
    play: "▶",
    "play.fill": "▶",
    "rectangle.3.group": "▦",
    "exclamationmark.triangle.fill": "⚠️",
    "slider.horizontal.3": "🎚️",
};
export const bootstrapIconMap = {
    "arrow.clockwise": "arrow-clockwise",
    "arrow.clockwise.circle": "arrow-clockwise",
    "arrow.down.circle": "arrow-down-circle",
    "arrow.triangle.2.circlepath": "arrow-repeat",
    "arrow.triangle.merge": "intersect",
    checklist: "card-checklist",
    "checkmark.circle.fill": "check-circle-fill",
    "checkmark.seal": "patch-check",
    "checkmark.seal.fill": "patch-check-fill",
    "doc.text": "file-text",
    "doc.text.magnifyingglass": "file-earmark-text",
    externaldrive: "device-hdd",
    "externaldrive.connected.to.line.below": "hdd-network",
    folder: "folder",
    "folder.badge.gearshape": "folder-symlink",
    gearshape: "gear",
    globe: "globe2",
    "number.circle": "123",
    play: "play",
    "play.fill": "play-fill",
    "rectangle.3.group": "collection",
    scissors: "scissors",
    "square.grid.3x3": "grid-3x3",
    stethoscope: "activity",
    tablecells: "table",
    terminal: "terminal",
    "text.badge.checkmark": "file-earmark-check",
    "text.page": "file-earmark-text",
    "text.page.badge.magnifyingglass": "file-earmark-richtext",
    trash: "trash",
    "trash.fill": "trash-fill",
    tree: "diagram-3",
    "waveform.path.ecg": "activity",
    "waveform.path.ecg.rectangle": "clipboard2-pulse",
    xmark: "x",
    "exclamationmark.triangle.fill": "exclamation-triangle-fill",
    "slider.horizontal.3": "sliders",
};
export function normalizeIconSet(value) {
    return value === "emoji" ? "emoji" : "platform";
}
export function normalizeColorTheme(value) {
    return value === "light" || value === "dark" ? value : "system";
}
